### ISSUE TITLE
Example code does not work

### ISSUE THREAD

**Issue by mountaindude** [jparis/qrs-interact#41]
The example code for getting a list of all tags doesn't work, it throws an error on the forEach statement. 
Using just the same console.log(result) as in the first example works well, that's probably preferred as an example.

**Comment by jparis** [comment]
Sorry about that! Forgot to update the docs! All good to go now, it should be working! Feel free to close this if it's working on your end.

**Comment by mountaindude** [comment]
works a treat - nice!
