### ISSUE TITLE
question: more examples?

### ISSUE THREAD

**Issue by QHose** [jparis/qrs-interact#51]
hi,

Thanks for creating this handy repo. 

I wondered do you have some more example on how to

- supply certificate
- add querystrings
- add post body (e.g. a zip file for uploading extensions, or {name: myStream}

thanks!

**Comment by QHose** [comment]
In order to try to answer my own question... 

in the [source](https://github.com/eapowertools/qrs-interact/blob/master/qrsInteract.js#L122) you will find this function for a post, the second param is the body.
`this.Post = function (path, body, sendType) {`

**Comment by jparis** [comment]
Ah, totally missed the notification on this. I will try to add some more examples soon!

**Comment by jparis** [comment]
Added a few more examples here, as well as different ways to user certificates (custom configuration).

https://github.com/eapowertools/qrs-interact/wiki
