### ISSUE TITLE
This project is marked as inactive.  Is it still considered valid?

### ISSUE THREAD

**Issue by mariorubbo** [jparis/qrs-interact#57]
was trying to find the latest (and best) way to connect to the Repository server from NodeJS

**Comment by jparis** [comment]
Yep, I still try to keep it up to date and fix any bugs, but I haven't ran into any in a while and it feels pretty stable, so just marked it inactive.

As per repostatus: https://www.repostatus.org/#inactive
```Inactive – The project has reached a stable, usable state but is no longer being actively developed; support/maintenance will be provided as time allows.```
