### ISSUE TITLE
console.log ?

### ISSUE THREAD

**Issue by countnazgul** [jparis/qrs-interact#60]
Why is there `console.log` ([at row 85](https://github.com/eapowertools/qrs-interact/blob/39ee5977cf35150cd68570fa7ef626e2f0504813/qrsInteract.js#L85))?

Its not a big deal but its bugging me (sometimes :)))) )

**Comment by jparis** [comment]
Probably was debugging and forgot to take it out... will do that...

**Comment by jparis** [comment]
Done.

**Comment by countnazgul** [comment]
Thanks!
