### ISSUE TITLE
Warning: `(node:126) Warning: a promise was rejected with a non-error: [object String]`

### ISSUE THREAD

**Issue by sobolevn** [jparis/qrs-interact#68]
This happens because these lines `reject` with `string` type (and many other lines too):

- https://github.com/jparis/qrs-interact/blob/master/qrsInteract.js#L90
- https://github.com/jparis/qrs-interact/blob/master/qrsInteract.js#L116
- https://github.com/jparis/qrs-interact/blob/master/qrsInteract.js#L120

It should be:

```js
reject(new Error('...'))
```

**Comment by jparis** [comment]
Will take a look and update. Thanks.

**Comment by jparis** [comment]
fixed in 6.1.0
