### ISSUE TITLE
404, 403 http response codes are not caught 

### ISSUE THREAD

**Issue by miguki** [jparis/qrs-interact#71]
Hello, another issue I found is that when 404 or 403 http response codes are encountered the error is not thrown, please consider adding some code throwing error just after receiving response from server, as no event is fired when 404 or 403 occurs in current code

 Article for reference: https://stackoverflow.com/questions/15915352/node-js-http-get-request-error-event-not-picking-up-404-or-403

**Comment by jparis** [comment]
There was a bug in the PUT call, should be fixed in next release. Re-open if it's not with an example and I'll get it fixed.

**Comment by jparis** [comment]
fixed in 6.1.0
