### ISSUE TITLE
Remote connection without certificates

### ISSUE THREAD

**Issue by countnazgul** [jparis/qrs-interact#73]
Im able to authenticate and get sessionId for the user prior to the request to the repository. Is there a way to provide the session as a header/cookie when making the request with qrs-interact?

When `certificates` section is missing from the config im getting an error that the `client.pem` is not found (searched in the default location `Exported Certificates\.Local Certificates`

Or im doing something wrong?

**Comment by jparis** [comment]
I think I have it working for JWT, but that was the only support I added. It's in https://github.com/jparis/qrs-interact/blob/master/qrsInteractFactory.js roughly line 70.

Could add a condition for no certs and no header with 'Bearer'. Or just remove the last else condition and trust your config is good.
