### ISSUE TITLE
Broken header code for POST?

### ISSUE THREAD

**Issue by mountaindude** [jparis/qrs-interact#79]
@jparis 

Think there might be a small bug in the POST code.
https://github.com/jparis/qrs-interact/blob/1580fb5244bd04d1d734bb053d7b5af6395d8f48/qrsInteract.js#L144

`r.headers...` throws an error. 
I suspect the "r" should be a "requestParams".

Will try that and open a PR if needed.

/Göran

**Comment by mountaindude** [comment]
Yup, that seems to fix it. Will open a PR.

**Comment by mountaindude** [comment]
PR created.

**Comment by jparis** [comment]
Yep, my bad. Made some changes and totally misssed that one. Will merge in a sec.
